services:
  caller:
    image: alchemyst/caller:local
    build:
      context: ../..
      dockerfile: deploy/docker/caller.Dockerfile
    environment:
      III_URL: ${III_URL:-ws://10.10.1.11:49134}
    restart: unless-stopped
